title: DeepDive
baseurl: ""

date_format: "%Y-%m-%d"

markdown: kramdown
highlighter: rouge
# Build settings
kramdown:
  input: GFM
permalink: pretty

# Third-party services
# just leave someone empty to disable it
google_analytics: UA-89686579-1
disqus_shortname: deepdive-1

timezone: Asia/Taipei

gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji
  - jekyll-mentions
